fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: ipes.lagache@gmail.com
        sender_name: SESAME
    registration:
        form:
            type: App\Form\RegistrationFormType
        confirmation:
            from_email: 
                address: registred@sesame.be
                sender_name: Sesame Register