# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true
            remember_me:
                secret: '%kernel.secret%'

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: /home, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: /, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: /thesaurus, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/, role: ROLE_USER, requires_channel: https }
        #Add more routes here in order to prevent access to unauthorized.