vich_uploader:
    db_driver: orm

    mappings:
        gesture_cover:
            uri_prefix: thesaurus/gestures/images
            upload_destination: '%kernel.project_dir%/public/thesaurus/gestures/images'

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true


        gesture_video:
            uri_prefix: /thesaurus/gestures/videos
            upload_destination: '%kernel.project_dir%/public/thesaurus/gestures/videos'

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        gesture_profileVideo:
            uri_prefix: /thesaurus/gestures/videos
            upload_destination: '%kernel.project_dir%/public/thesaurus/gestures/videos'

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
