#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    # SOLUTION FOUND: https://stackoverflow.com/questions/48446371/unrecognized-option-resource-under-fos-user

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"